print("Dame la cantidad de bultos de cemento")
bultos=int(input())
print("Dame el precio por bulto")
precio=float(input())
antesIVA=(bultos*precio)
print("El precio antes de impuestos es",antesIVA)
IVA=(antesIVA*0.16)
print("los impuestos son", IVA)
totalP=(antesIVA+IVA)
print("El total a pagar es", totalP)