print("Dame la primera coordenada")
x1=float(input())
print("Dame la segunda coordenada")
y1=float(input())
print("Dame la tercera coordenada")
x2=float(input())
print("Dame la cuarta coordenada")
y2=float(input())
m=(y2-y1)/(x2-x1)
print("La pendiente es",m)